def on_button_pressed_a():
    basic.show_string("SELF DESTURCT ")
    basic.show_string("1:00 MINUTE LEFT")
    basic.show_string("59")
    basic.show_string("58")
    basic.show_string("57")
    basic.show_string("56")
    basic.show_string("55")
    basic.show_string("54")
    basic.show_string("53")
    basic.show_string("52")
    basic.show_string("51")
    basic.show_string("50")
    basic.show_string("49")
    basic.show_string("48")
    basic.show_string("47")
    basic.show_string("46")
    basic.show_string("45")
    basic.show_string("44")
    basic.show_string("43")
    basic.show_string("42")
    basic.show_string("41")
    basic.show_string("40")
    basic.show_string("39")
    basic.show_string("38")
    basic.show_string("37")
    basic.show_string("36")
    basic.show_string("35")
    basic.show_string("34")
    basic.show_string("33")
    basic.show_string("32")
    basic.show_string("31")
    basic.show_string("30")
    basic.show_string("29")
    basic.show_string("28")
    basic.show_string("27")
    basic.show_string("26")
    basic.show_string("25")
    basic.show_string("24")
    basic.show_string("23")
    basic.show_string("22")
    basic.show_string("21")
    basic.show_string("20")
    basic.show_string("19")
    basic.show_string("18")
    basic.show_string("17")
    basic.show_string("16")
    basic.show_string("15")
    basic.show_string("14")
    basic.show_string("13")
    basic.show_string("12")
    basic.show_string("11")
    basic.show_string("10")
    basic.show_string("9")
    basic.show_string("8")
    basic.show_string("7")
    basic.show_string("6")
    basic.show_string("5")
    basic.show_string("4")
    basic.show_string("3")
    basic.show_string("2")
    basic.show_string("1")
    basic.show_string("0")
    music.set_built_in_speaker_enabled(True)
    music.play(music.string_playable("C D C D C D C D ", 120),
        music.PlaybackMode.LOOPING_IN_BACKGROUND)
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
    music.set_built_in_speaker_enabled(False)
    basic.show_string("CANCELED")
input.on_button_pressed(Button.B, on_button_pressed_b)

def on_forever():
    if input.logo_is_pressed():
        music.set_built_in_speaker_enabled(True)
        basic.show_string("SELF DESTURCT ")
        for index in range(5):
            music.play(music.string_playable("C D C D C D C D ", 120),
                music.PlaybackMode.UNTIL_DONE)
basic.forever(on_forever)
