input.onButtonPressed(Button.A, function () {
    basic.showString("SELF DESTURCT ")
    basic.showString("1:00 MINUTE LEFT")
    basic.showString("59")
    basic.showString("58")
    basic.showString("57")
    basic.showString("56")
    basic.showString("55")
    basic.showString("54")
    basic.showString("53")
    basic.showString("52")
    basic.showString("51")
    basic.showString("50")
    basic.showString("49")
    basic.showString("48")
    basic.showString("47")
    basic.showString("46")
    basic.showString("45")
    basic.showString("44")
    basic.showString("43")
    basic.showString("42")
    basic.showString("41")
    basic.showString("40")
    basic.showString("39")
    basic.showString("38")
    basic.showString("37")
    basic.showString("36")
    basic.showString("35")
    basic.showString("34")
    basic.showString("33")
    basic.showString("32")
    basic.showString("31")
    basic.showString("30")
    basic.showString("29")
    basic.showString("28")
    basic.showString("27")
    basic.showString("26")
    basic.showString("25")
    basic.showString("24")
    basic.showString("23")
    basic.showString("22")
    basic.showString("21")
    basic.showString("20")
    basic.showString("19")
    basic.showString("18")
    basic.showString("17")
    basic.showString("16")
    basic.showString("15")
    basic.showString("14")
    basic.showString("13")
    basic.showString("12")
    basic.showString("11")
    basic.showString("10")
    basic.showString("9")
    basic.showString("8")
    basic.showString("7")
    basic.showString("6")
    basic.showString("5")
    basic.showString("4")
    basic.showString("3")
    basic.showString("2")
    basic.showString("1")
    basic.showString("0")
    music.setBuiltInSpeakerEnabled(true)
    music.play(music.stringPlayable("C D C D C D C D ", 120), music.PlaybackMode.LoopingInBackground)
})
input.onButtonPressed(Button.B, function () {
    music.setBuiltInSpeakerEnabled(false)
    basic.showString("CANCELED")
})
basic.forever(function () {
    if (input.logoIsPressed()) {
        music.setBuiltInSpeakerEnabled(true)
        basic.showString("SELF DESTURCT ")
        for (let index = 0; index < 5; index++) {
            music.play(music.stringPlayable("C D C D C D C D ", 120), music.PlaybackMode.UntilDone)
        }
    }
})
